version: '3.7' # specify docker-compose version

services:
  mongo: #database 
    container_name:  mongo
    image: mongo:4.4
    hostname: mongo
    restart: always
    environment: 
      TZ: "America/Bogota" #Time zone south america
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017  
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - angular-chat-net
  backend: #name backend service spring boot app
    build: angular-chat-socket-broker
    ports:
       - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=pdn
      - MONGO_HOST=mongo
    restart: on-failure
    healthcheck:
      test: curl -m 5 --silent --fail --request GET http://localhost:8080/actuator/health | jq --exit-status -n 'inputs | if has("status") then .status=="UP" else false end' > /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 10   
    depends_on: 
       - mongo
    networks:
       - angular-chat-net    
  frontend: #name front-end  angular
    build: angular-chat-socket-front
    ports:
       - "4200:80"
    depends_on:
      - backend
networks:
 angular-chat-net:
    driver: bridge
